[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[template.environment]
  NEXT_PUBLIC_SANITY_PROJECT_ID="Your Sanity Project Id"
  NEXT_PUBLIC_SANITY_DATASET="Your Sanity Dataset"
  SANITY_API_WRITE_TOKEN="Your Sanity API Write Token"
  SANITY_API_READ_TOKEN="Your Sanity API Read Token"
